version: "3.3"

services:
  web:
    build: .
    restart: always
    ports:
      - 8000
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:5.0.4-alpine
    restart: always
    ports:
      - 6379:6379

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
